version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

sphinx:
  configuration: jax_tpu_embedding/sparsecore/docs/conf.py

python:
  install:
    - requirements: jax_tpu_embedding/sparsecore/docs/requirements.txt
