name: Build and test

on:
  # Only run workflow on pushes to main (includes PR merge), and on
  # opened pull-requests.
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read      # Lets the job check out your code
  actions: write      # Lets the job write (save) the cache

jobs:
  build-and-test-cpu:
    runs-on: linux-x86-n4-16
    container: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python 3.12
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.12'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade --root-user-action=ignore pip setuptools wheel
          bash tools/install_bazelisk.sh

      # --- FOR PULL REQUESTS ---
      # Restore the cache from the main branch's base commit.
      - if: github.event_name == 'pull_request'
        name: Mount bazel cache (pull-request)
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: "/__w/.cache/bazel"
          key: bazel-py3.12-${{ github.base_ref }}-${{ github.event.pull_request.base.sha }}
          restore-keys: |
            bazel-py3.12-${{ github.base_ref }}
            bazel-py3.12-
            bazel-

      # --- FOR MAIN PUSHES AND MERGES ---
      # Restore the cache from the previous commit.
      - if: github.event_name != 'pull_request'
        name: Mount bazel cache (main)
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: "/__w/.cache/bazel"
          # Try to find the cache from the exact commit *before* this push
          key: bazel-py3.12-${{ github.ref_name }}-${{ github.event.before }}
          # Fall back to the most recent cache for the main branch
          restore-keys: |
            bazel-py3.12-${{ github.ref_name }}
            bazel-py3.12-
            bazel-

      - name: Build all targets
        run: |
          export HERMETIC_PYTHON_VERSION=3.12
          bazel build --config=public_cache //... --build_tag_filters=-oss_exclude

      - name: Build wheel
        run: |
          export HERMETIC_PYTHON_VERSION=3.12
          bazel run --config=public_cache //tools:build_wheel

      - name: Run CPU tests
        run: |
          export HERMETIC_PYTHON_VERSION=3.12
          bazel test --config=public_cache --build_tests_only --test_tag_filters=-requires-tpu --test_output=errors --keep_going //...

      - name: Check disk space
        run: |
          df -h --total
          du -sh /__w/.cache/bazel

      # --- SAVE NEW CACHE ---
      - name: Save bazel cache (main)
        if: github.event_name != 'pull_request'
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: "/__w/.cache/bazel"
          key: bazel-py3.12-${{ github.ref_name }}-${{ github.sha }}
