name: Lint

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint_and_typecheck:
    runs-on: linux-x86-n4-16
    container: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python 3.12
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
        with:
          python-version: '3.12'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install lint and project dependencies
        run: |
          git config --global --add safe.directory "*"
          python -m pip install --upgrade --root-user-action=ignore pip setuptools wheel pyrefly pre-commit
          python -m pip install --root-user-action=ignore -r third_party/py/requirements_lock_3_12.txt

      - name: Run pre-commit checks
        run: pre-commit run --show-diff-on-failure --color=always --all-files
